import Link from "next/link";
import { Radar } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <nav className="border-b sticky top-0 bg-white/80 backdrop-blur-sm z-50">
        <div className="max-w-4xl mx-auto px-4 h-16 flex items-center">
          <Link href="/" className="flex items-center gap-2">
            <Radar className="h-7 w-7 text-primary" />
            <span className="text-lg font-bold">PhDRadar</span>
          </Link>
        </div>
      </nav>
      <article className="max-w-4xl mx-auto px-4 py-12 prose prose-gray">
        <h1>Terms of Service</h1>
        <p className="text-muted-foreground">Last updated: April 12, 2026</p>

        <h2>1. Acceptance of Terms</h2>
        <p>By accessing or using PhDRadar (&quot;the Service&quot;), operated by Shammas Development LLC, you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>

        <h2>2. Description of Service</h2>
        <p>PhDRadar is an AI-powered platform that helps prospective PhD students discover professors, analyze research fit, and draft outreach emails. The Service provides tools for research and organization — it does not guarantee admission, funding, or any specific outcome.</p>

        <h2>3. User Accounts</h2>
        <ul>
          <li>You must provide accurate information when creating an account.</li>
          <li>You are responsible for maintaining the security of your account credentials.</li>
          <li>You must be at least 18 years old to use the Service.</li>
          <li>One person per account. Account sharing is not permitted.</li>
        </ul>

        <h2>4. Acceptable Use</h2>
        <p>You agree NOT to:</p>
        <ul>
          <li>Send spam, unsolicited bulk emails, or harassing messages to professors using content generated by the Service.</li>
          <li>Misrepresent your identity or qualifications in outreach emails.</li>
          <li>Use the Service to scrape, collect, or harvest professor contact information for purposes outside of legitimate PhD application outreach.</li>
          <li>Attempt to reverse-engineer, decompile, or extract the AI models or algorithms.</li>
          <li>Use automated tools (bots, scrapers) to access the Service beyond normal usage.</li>
        </ul>

        <h2>5. AI-Generated Content</h2>
        <ul>
          <li>Emails and analyses generated by AI are suggestions only. You are solely responsible for reviewing, editing, and personalizing all content before sending.</li>
          <li>PhDRadar is not responsible for the content of emails you send to professors.</li>
          <li>AI outputs may contain inaccuracies. Always verify information independently.</li>
        </ul>

        <h2>6. Professor Data</h2>
        <p>All professor data is sourced from publicly available information (university websites, Google Scholar, NSF/NIH databases, etc.). Professors may request removal of their data by contacting us.</p>

        <h2>7. Payments and Subscriptions</h2>
        <ul>
          <li>Free tier users have limited access as described on the pricing page.</li>
          <li>Paid subscriptions are billed monthly. You may cancel at any time.</li>
          <li>Refunds are provided on a case-by-case basis within the first 14 days.</li>
        </ul>

        <h2>8. Intellectual Property</h2>
        <p>The Service, including its design, code, AI models, and content, is owned by Shammas Development LLC. User-generated content (notes, emails you draft) remains yours.</p>

        <h2>9. Privacy</h2>
        <p>Your use of the Service is also governed by our <Link href="/privacy" className="text-primary hover:underline">Privacy Policy</Link>.</p>

        <h2>10. Limitation of Liability</h2>
        <p>PhDRadar is provided &quot;as is&quot; without warranties of any kind. We are not liable for any damages arising from your use of the Service, including but not limited to rejection from PhD programs, failed professor outreach, or inaccurate data.</p>

        <h2>11. Termination</h2>
        <p>We may suspend or terminate your account for violation of these terms. You may delete your account at any time from the Settings page.</p>

        <h2>12. Changes to Terms</h2>
        <p>We may update these terms. Continued use after changes constitutes acceptance.</p>

        <h2>13. Contact</h2>
        <p>Questions? Contact us at <a href="mailto:legal@phdradar.com" className="text-primary">legal@phdradar.com</a>.</p>
      </article>
    </div>
  );
}
